### ISSUE TITLE
No informative families for Affected [ALL]

### ISSUE THREAD

**Issue by ghost** [mlebeur/merlin#2]
Hi. This problem is resolved. Please delete or close this ticket.

**Comment by arton2008** [comment]
Here is an update. I made changes to my ped file and broke down the pedigree to smaller pedigrees. This analysis worked and generated some results. The full pedigree has second, third and fourth cousins without any data from the parents or grand parents. Now my questions is how many generations with unknown genotypes can we indicate in a ped file?
